### ISSUE TITLE
documentation broken link

### ISSUE THREAD

**Issue by UlasSAYGINIM** [ICanBoogie/ICanBoogie#13]
hi , there is broken link in documentation.

on this page.
https://icanboogie.org/docs/4.0/autoconfig

this sentence : The file must match the composer-schema.json schema.
composer-schema.json is link to this link.
https://github.com/ICanBoogie/ICanBoogie/blob/master/lib/Autoconfig/composer-schema.json

**Comment by olvlvl** [comment]
Thanks for reporting. It's fixed now.
